---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

#
# platform-specific variables
#

- name: set java architecture
  set_fact:
    jdk_arch: "{{ 'i586'  if ansible_architecture == 'i386' else 'x64' }}"

- name: set java OS for Linux
  set_fact:
    jdk_os: linux
  when: ansible_system == 'Linux'

- name: set java OS for Mac OS X
  set_fact:
    jdk_os: macosx
  when: ansible_os_family == 'Darwin'


#
# version-specific variables
#

- name: check if java_version is semver
  set_fact:
    java_version_is_semver: "{{ java_version is regex(\"\\d+\\.\\d+\\.\\d+\") | bool }}"

- name: include semver variables
  include_tasks: set-role-variables-semver.yml
  when: java_version_is_semver is true

- name: include version / subversion variables
  include_tasks: set-role-variables-version-subversion.yml
  when: java_version_is_semver is false


- name: compose url for downloading file, if necessary
  set_fact:
    jdk_tarball_url:  "http://download.oracle.com/otn-pub/java/jdk/{{ jdk_version_detail }}/{{ jdk_tarball_file }}"
  when: jdk_version_detail is defined and jdk_tarball_hash is not defined

- name: compose url for downloading file, if necessary
  set_fact:
    jdk_tarball_url: "http://download.oracle.com/otn-pub/java/jdk/{{ jdk_version_detail }}/{{ jdk_tarball_hash }}/{{ jdk_tarball_file }}"
  when: jdk_version_detail is defined and jdk_tarball_hash is defined


#
# directories
#

- name: set java installation directory on Debian platforms
  set_fact:
    java_install_dir: /usr/lib/jvm
    java_default_link_name: default-java
    java_home: /usr/lib/jvm/default-java
  when: ansible_os_family == "Debian"

- name: set java installation directory on non-Debian platforms
  set_fact:
    java_install_dir: /usr/java
    java_default_link_name: default
    java_home: /usr/java/default
  when: ansible_os_family != "Debian" and ansible_os_family != "Darwin"
