---
# file: use-tarball.yml
# install Oracle JDK 1.x on Mac OS X
#
# See: #      https://docs.oracle.com/javase/8/docs/technotes/guides/install/mac_jdk.html
#

- name: mount the downloaded dmg
  shell: hdiutil attach "{{ java_download_path }}/{{ jdk_tarball_file }}.dmg"

- name: set dmg name (semver)
  set_fact:
    dmg_name: "JDK {{ java_version }}"
  when: java_version_is_semver is true

- name: set dmg name (version / subversion)
  set_fact:
    dmg_name: "JDK {{ java_version }} Update {{ java_subversion }}"
  when: java_version_is_semver is false

- name: install the pkg file from the dmg
  become: yes
  become_method: sudo
  shell: >
    installer
    -pkg "/Volumes/{{ dmg_name }}/{{ dmg_name }}.pkg"
    -target /

- name: unmount the downloaded dmg
  shell: hdiutil detach "/Volumes/{{ dmg_name }}"
